# Generated by Django 2.2.1 on 2019-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpaste',
            name='language',
            field=models.CharField(choices=[('Python', 'PYTHON'), ('CPP', 'C/C++'), ('Java', 'Java'), ('JavaScript', 'JS'), ('TextFile', 'GEN')], default='TextFile', max_length=10),
        ),
        migrations.AlterField(
            model_name='textpaste',
            name='Text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='textpaste',
            name='Username',
            field=models.CharField(max_length=20),
        ),
    ]
