# Generated by Django 2.2.1 on 2019-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_auto_20190528_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpaste',
            name='language',
            field=models.CharField(choices=[('Python', 'PYTHON'), ('CPP', 'C/C++'), ('Java', 'Java'), ('JS', 'JavaScript'), ('GEN', 'TextFile')], default='TextFile', max_length=10),
        ),
    ]
