# Generated by Django 2.2.1 on 2019-05-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0005_auto_20190528_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpaste',
            name='language',
            field=models.CharField(choices=[('python', 'PYTHON'), ('C++', 'C/C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('none', 'TextFile')], default='GEN', max_length=10),
        ),
    ]
