# Generated by Django 2.2.1 on 2019-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0006_auto_20190528_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpaste',
            name='language',
            field=models.CharField(choices=[('python', 'PYTHON'), ('C++', 'C/C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('none', 'TextFile')], default='none', max_length=10),
        ),
    ]
